racing:
  hostname: 206.81.18.153
  user: magnus
  port: 22
  deploy_path: ~/vhosts/race
  configFile: ~/.ssh/config
  identityFile: ~/.ssh/id_rsa
  forwardAgent: true
  multiplexing: false
  options:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  stage: staging
  roles:
    - app
